### ISSUE TITLE
Tracking issue for the traffic isolation feature

### ISSUE THREAD

**Issue by lionelvillard** [knative-extensions/net-kourier#876]
This issue tracks the traffic isolation feature tasks.

Feature Track: https://docs.google.com/document/d/11hViPJlmI4ftcZVkT8x6Au4cCxRncsEq7M6UCd_UKJ8/edit

Alpha (disabled by default):

- [ ] Add port-level traffic isolation. [PR](https://github.com/knative-sandbox/net-kourier/pull/852)
- [ ] Validate annotations. [Issue](https://github.com/knative-sandbox/net-kourier/issues/875)
- [ ] Add support for internal traffic encryption. [Issue](https://github.com/knative-sandbox/net-kourier/issues/871)
- [ ] Add e2e tests. [Issue](https://github.com/knative-sandbox/net-kourier/issues/870)
- [ ] Extract utility function for getting the listener port annotation value
- [ ] Add documentation [PR](https://github.com/knative-sandbox/net-kourier/pull/852)

Beta (disabled by default):

GA (disabled by default):

/cc @skonto @nak3 @evankanderson @rhuss

**Comment by dddddai** [comment]
Hi community!
> Extract utility function for getting the listener port annotation value

Given we are going to support this feature for other ingress implementations(istio, gateway-api...), does it make sense to use a general annotation(like `ingress.networking.knative.dev/listener-port`) instead of a kourier one(i.e. `kourier.knative.dev/listener-port`)?

**Comment by dddddai** [comment]
Similar question for the `traffic-isolation` flag in `config-kourier`, I think we probably need to move it to `config-network`?

**Comment by ReToCode** [comment]
> Given we are going to support this feature for other ingress implementations(istio, gateway-api...)

I don't think we are there yet. The kourier implementation is currently more in a PoC state (see the open tasks above) and it has not yet been decided if we go along with this approach.

**Comment by dddddai** [comment]
IIUC https://github.com/knative/serving/issues/13780#issue-1617832882 is the plan?

**Comment by ReToCode** [comment]
Ah, then maybe @evankanderson can comment on that?

**Comment by evankanderson** [comment]
From more customer experience, it seems like moving to a port-per-Route approach for internal traffic would have a few benefits:

1. Enable use of NetworkPolicy for security
2. Simplify behavior for clients (can use `name` without the `namespace`, similar to other Kubernetes services)

Of the two, the second item is more compelling, but the combination of the two suggests this is worth exploring as an installation option.

**Comment by dddddai** [comment]
> From more customer experience, it seems like moving to a port-per-Route approach for internal traffic would have a few benefits

Does `port-per-Route` mean assigning a dedicated port for each ksvc?
> 1. Enable use of NetworkPolicy for security
> 2. Simplify behavior for clients (can use `name` without the `namespace`, similar to other Kubernetes services)

I think port-per-namespace(tenant) already satisfies these? Please correct me if I'm wrong

**Comment by rhuss** [comment]
So, how should we proceed with this issue ? We have already https://github.com/knative-sandbox/net-kourier/pull/852 merged but are not very far with this feature. Is there any interest in continuing the work or should we revert #852 ?

**Comment by dprotaso** [comment]
@rhuss I think it would be good to explore how to do this feature with the Gateway API - and if there are gaps in the API open the necessary upstream issues.

**Comment by ReToCode** [comment]
+1 @dprotaso 

If no one want is up to finish the work, I'd opt for removing the current code, as it is not really documented and untested. It just makes our current implementation more complex to maintain. WDYT @nak3 , @skonto ?

**Comment by rhuss** [comment]
+1 for rolling back any changes and restarting the efforts with focussing on the Gateway API

**Comment by ReToCode** [comment]
Reopening to track [this](https://github.com/knative-sandbox/net-kourier/issues/876#issuecomment-1655450269).

/assign
